
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

# Personal challenge: Find sum of even or odd value terms up to given input value.


limit = int(input('Find sum of fibonacci sequence to which value? > '))

evenSum = []
oddSum = []
fibonacci = []

n1, n2 = 0, 1
fibonacci.append(n1)
fibonacci.append(n2)
while n1 <= limit:
    n1, n2 = n2, n1 + n2
    fibonacci.append(n2)
    limit -= 1

for i in fibonacci:
    if i % 2 == 0:
        evenSum.append(i)
    else:
        oddSum.append(i)

print('Even Sum: ' + sum(evenSum))
print('Odd Sum: ' + sum(oddSum))
